#include "valkyrie/drivetrain/TractionController.h"

#define MIN_SLIP_RATIO = 0.01f
#define MAX_SLIP_RATIO = 0.40f
#define SIGMOID_K = 10
#define FORCE_ACCELERATION_MULTIPLIER = 0.7f
#define INTERTIAL_VELOCITY_THRESHOLD = 0.01_mps
#define VELOCITY_DIFFERENCE_THRESHOLD = 1.0_mps
#define MIN_SLIPPING_TIME = 0.5_s
#define VELOCITY_REQUEST_THRESHOLD = 0.05_mps
#define WHEEL_SPEED_THRESHOLD = 0.05_mps
#define STATIC_FORCE_ACCELERATE_TRIGGER_TIME = 0.1_s
#define DYNAMIC_FORCE_ACCELERATE_TRIGGER_TIME = 0.2_s
#define FORCE_ACCELERATE_TIME = 2.0_s