default:
  image: lilshan24/valor-pipeline:latest

build:
  stage: build
  script:
    - ./gradlew format build

formatter:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
    - cp $PRIVATE_KEY ~/.ssh/id_ed25519
    - cp $PUBLIC_KEY ~/.ssh/id_ed25519.pub
    - |
      cat <<EOF > ~/.ssh/config
      Host git.valor6800.com
        HostName git.valor6800.com
        Port 6822
        IdentityFile ~/.ssh/id_ed25519
      EOF
    - chmod 600 ~/.ssh/id_ed25519
    - git config --global user.email "bot@noreply.git.valor6800.com"
    - git config --global user.name "Formatter Bot"
  script:
    - ./gradlew format
    - git add .
    - git remote rm origin
    - git remote add origin git@git.valor6800.com:$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
    - (git commit -m "[bot] Fix formatting" && git push origin HEAD:$CI_COMMIT_REF_NAME -o ci.skip) || true

doxygen:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - ./gradlew doxygen
    - mv docs/html public
  artifacts:
    paths:
      - public
    expire_in: 1 week

pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - ls -l public
  artifacts:
    paths:
      - public
